- name: pod
  type: group
  description: >
    kubernetes pod metrics
  release: ga
  fields:
    - name: host_ip
      type: ip
      description: >
        Kubernetes pod host IP
    - name: status
      type: group
      description: >
        Kubernetes pod status metrics
      fields:
        - name: phase
          type: keyword
          description: >
            Kubernetes pod phase (Running, Pending...)
        - name: ready
          type: keyword
          description: >
            Kubernetes pod ready status (true, false or unknown)
        - name: scheduled
          type: keyword
          description: >
            Kubernetes pod scheduled status (true, false, unknown)
    - name: owner
      type: group
      description: >
        Kubernetes job owner information
      fields:
        - name: name
          type: keyword
          description: >
            The name of the resource that owns this job
        - name: kind
          type: keyword
          description: >
            The kind of resource that owns this job (eg. "CronJob")
        - name: is_controller
          type: keyword
          description: >
            Owner is controller ("true", "false", or "<none>")
