- name: replicaset
  type: group
  description: >
    kubernetes replica set metrics
  release: ga
  fields:
    - name: replicas
      type: group
      description: >
        Kubernetes replica set paused status
      fields:
        - name: available
          type: long
          description: >
            The number of replicas per ReplicaSet
        - name: desired
          type: long
          description: >
            The number of replicas per ReplicaSet
        - name: ready
          type: long
          description: >
            The number of ready replicas per ReplicaSet
        - name: observed
          type: long
          description: >
            The generation observed by the ReplicaSet controller
        - name: labeled
          type: long
          description: >
            The number of fully labeled replicas per ReplicaSet
        - name: owner
          type: group
          description: >
            Kubernetes replicaset owner information
          fields:
            - name: name
              type: keyword
              description: >
                The name of the resource that owns this replicaset
            - name: kind
              type: keyword
              description: >
                The kind of resource that owns this replicaset (eg. "Deployment")
            - name: is_controller
              type: keyword
              description: >
                Owner is controller ("true", "false", or "<none>")
